# All data fields for the customer object

customer_data = {
    # "_id":"",
    "company_id": "",
    "cuid":,
    "first_name": "",
    "last_name": "",
    "email": "",
    "phone": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "zip_code": "",
    "notes": "",
    "job_notes": "",
    "alt_email": "",
    "alt_phone": "",
    "secondary_first_name": "",
    "secondary_last_name": "",
    "secondary_email": "",
    "secondary_phone": "",
    "account_type": "individual",
    "company_name": "",
    "status": "current customer",
    "has_different_billing_address":,
    "billing_address_1": "",
    "billing_address_2": "",
    "billing_city": "",
    "billing_state": "",
    "billing_zip_code": "",
    "assigned_to": "",
    "phone_e164": "",
    "fax": "",
    "skype": "",
    "dial_phone": "",w
    "mobile_phone": "",
    "website": "",
    "updated_at": "",
    "created_at": "",
    "searchable": "",
    "sort_key": "",
    "tags": [""],
    "has_available_forms": True,
    "customfields": [],
    "parent": None
}

# All data fields for the lead object which mimicks the customer object

lead_data = {
    "_id": "",
    "first_name": "",
    "last_name": "",
    "email": "",
    "company_name": "",
    "phone": "",
    "address_1": "",
    "address_2": "",
    "city": "",
    "state": "",
    "account_type": "",
    "zip_code": "",
    "notes": "",
    "secondary_email": "",
    "secondary_first_name": "",
    "secondary_last_name": "",
    "secondary_phone": "",
    "alt_email": "",
    "alt_phone": "",
    "status": "current customer",
    "deleted_at": "",
    "billing_address_1": "",
    "billing_address_2": "",
    "billing_city": "",
    "billing_state": "",
    "billing_zip_code": "",
    "has_different_billing_address": False,
    "tags": [],
    "customfields": [],
    "parent_id": None,
    "job_notes": "",
    "assigned_to": "",
    "phone_e164": ""
}
